# Site settings
title: Geek Code
header-img: img/home-bg.jpg
email: tossmilestone@gmail.com
copyright_name: tossmilestone
description: "For geek coding!"
baseurl: "/tossmilestone.github.io"
url: "http://tossmilestone.github.io/"
twitter_username: 
github_username:  tossmilestone
facebook_username:  
email_username:  tossmilestone@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
